# Pins from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
# so our packages is compatible with the choices made by conda-forge.
gmp:
  - '6'
fmt:
  - '11'
