{% set version = '3.1.4' %}

package:
  name: libintervalxt
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  # e-antic is not available on Windows yet
  skip: True  # [win]
  # e-antic is not available on macOS yet
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("libintervalxt", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - boost-cpp {{ boost_cpp }}
    - fmt {{ fmt }}
    - gmp {{ gmp }}
    - ppl

test:
  commands:
    - test -f ${PREFIX}/lib/libintervalxt.so

about:
  home: https://github.com/flatsurf/intervalxt
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Boshernitzan Algorithm with Interval Exchange Transformations
