# This file lists the dependencies needed to build and test all of libintervalxt.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: libintervalxt-build
channels:
  - conda-forge
dependencies:
  - automake
  - benchmark
  - boost-cpp
  - coreutils
  - cxx-compiler
  - libeantic>=2,<3
  - libflint
  - fmt=11
  - gmp
  - gmpxxll
  - libexactreal>=4,<5
  - libtool
  - make
  - ppl
  # valgrind is only needed for make check-valgrind
  # - valgrind
