{% set version = '3.1.4' %}

package:
  name: pyintervalxt
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  # libintervalxt is not available on Windows yet
  skip: True  # [win]
  # libintervalxt is not available on macOS yet
  skip: True  # [osx]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cppyythonizations
    - gmpxxyy
    - pyeantic >=1.0.0rc9,<2
    - pyexactreal >=1.4.3,<2
    - libintervalxt
  run:
    - boost-cpp
    - python
    # The latest cppyy has trouble with serializations, see https://bitbucket.org/wlav/cppyy/issues/364/segfault-in-clang-cxxrecorddecl
    - cppyy <2
    - cppyythonizations

test:
  imports:
    - pyintervalxt

about:
  home: https://github.com/flatsurf/intervalxt
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Boshernitzan Algorithm with Interval Exchange Transformations
