{% set version = '3.3.1' %}

package:
  name: pyintervalxt
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  # libintervalxt is not available on Windows yet
  skip: True  # [win]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cppyythonizations
    - gmpxxyy
    - libintervalxt
  run:
    - boost-cpp
    - python
    - cppyy
    - cppyythonizations
    - gmpxxyy

test:
  imports:
    - pyintervalxt

about:
  home: https://github.com/flatsurf/intervalxt
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Boshernitzan Algorithm with Interval Exchange Transformations
